# Generated by Django 4.0.5 on 2022-07-25 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='desc',
            new_name='message',
        ),
    ]
